use glfw::{Key, Modifiers};
use imgui::{Io, Key as ImGuiKey};

/// Handle changes in the key states.
pub fn handle_key(io: &mut Io, key: &Key, pressed: bool) {
    let igkey = match key {
        Key::Space => ImGuiKey::Space,
        Key::Apostrophe => ImGuiKey::Apostrophe,
        Key::Comma => ImGuiKey::Comma,
        Key::Minus => ImGuiKey::Minus,
        Key::Period => ImGuiKey::Period,
        Key::Slash => ImGuiKey::Slash,
        Key::Num0 => ImGuiKey::Keypad0,
        Key::Num1 => ImGuiKey::Keypad1,
        Key::Num2 => ImGuiKey::Keypad2,
        Key::Num3 => ImGuiKey::Keypad3,
        Key::Num4 => ImGuiKey::Keypad4,
        Key::Num5 => ImGuiKey::Keypad5,
        Key::Num6 => ImGuiKey::Keypad6,
        Key::Num7 => ImGuiKey::Keypad7,
        Key::Num8 => ImGuiKey::Keypad8,
        Key::Num9 => ImGuiKey::Keypad9,
        Key::Semicolon => ImGuiKey::Semicolon,
        Key::Equal => ImGuiKey::Equal,
        Key::A => ImGuiKey::A,
        Key::B => ImGuiKey::B,
        Key::C => ImGuiKey::C,
        Key::D => ImGuiKey::D,
        Key::E => ImGuiKey::E,
        Key::F => ImGuiKey::F,
        Key::G => ImGuiKey::G,
        Key::H => ImGuiKey::H,
        Key::I => ImGuiKey::I,
        Key::J => ImGuiKey::J,
        Key::K => ImGuiKey::K,
        Key::L => ImGuiKey::L,
        Key::M => ImGuiKey::M,
        Key::N => ImGuiKey::N,
        Key::O => ImGuiKey::O,
        Key::P => ImGuiKey::P,
        Key::Q => ImGuiKey::Q,
        Key::R => ImGuiKey::R,
        Key::S => ImGuiKey::S,
        Key::T => ImGuiKey::T,
        Key::U => ImGuiKey::U,
        Key::V => ImGuiKey::V,
        Key::W => ImGuiKey::W,
        Key::X => ImGuiKey::X,
        Key::Y => ImGuiKey::Y,
        Key::Z => ImGuiKey::Z,
        Key::Enter => ImGuiKey::Enter,
        Key::Escape => ImGuiKey::Escape,
        Key::Backspace => ImGuiKey::Backspace,
        Key::Tab => ImGuiKey::Tab,
        Key::LeftBracket => ImGuiKey::LeftBracket,
        Key::RightBracket => ImGuiKey::RightBracket,
        Key::Backslash => ImGuiKey::Backslash,
        Key::GraveAccent => ImGuiKey::GraveAccent,
        Key::CapsLock => ImGuiKey::CapsLock,
        Key::PrintScreen => ImGuiKey::PrintScreen,
        Key::ScrollLock => ImGuiKey::ScrollLock,
        Key::Pause => ImGuiKey::Pause,
        Key::Insert => ImGuiKey::Insert,
        Key::Home => ImGuiKey::Home,
        Key::PageUp => ImGuiKey::PageUp,
        Key::Delete => ImGuiKey::Delete,
        Key::End => ImGuiKey::End,
        Key::PageDown => ImGuiKey::PageDown,
        Key::Right => ImGuiKey::RightArrow,
        Key::Left => ImGuiKey::LeftArrow,
        Key::Down => ImGuiKey::DownArrow,
        Key::Up => ImGuiKey::UpArrow,
        Key::F1 => ImGuiKey::F1,
        Key::F2 => ImGuiKey::F2,
        Key::F3 => ImGuiKey::F3,
        Key::F4 => ImGuiKey::F4,
        Key::F5 => ImGuiKey::F5,
        Key::F6 => ImGuiKey::F6,
        Key::F7 => ImGuiKey::F7,
        Key::F8 => ImGuiKey::F8,
        Key::F9 => ImGuiKey::F9,
        Key::F10 => ImGuiKey::F10,
        Key::F11 => ImGuiKey::F11,
        Key::F12 => ImGuiKey::F12,
        Key::Kp0 => ImGuiKey::Keypad0,
        Key::Kp1 => ImGuiKey::Keypad1,
        Key::Kp2 => ImGuiKey::Keypad2,
        Key::Kp3 => ImGuiKey::Keypad3,
        Key::Kp4 => ImGuiKey::Keypad4,
        Key::Kp5 => ImGuiKey::Keypad5,
        Key::Kp6 => ImGuiKey::Keypad6,
        Key::Kp7 => ImGuiKey::Keypad7,
        Key::Kp8 => ImGuiKey::Keypad8,
        Key::Kp9 => ImGuiKey::Keypad9,
        Key::KpDecimal => ImGuiKey::KeypadDecimal,
        Key::KpDivide => ImGuiKey::KeypadDivide,
        Key::KpMultiply => ImGuiKey::KeypadMultiply,
        Key::KpSubtract => ImGuiKey::KeypadSubtract,
        Key::KpAdd => ImGuiKey::KeypadAdd,
        Key::KpEnter => ImGuiKey::KeypadEnter,
        Key::Menu => ImGuiKey::Menu,
        Key::KpEqual => ImGuiKey::KeypadEqual,
        Key::LeftShift => ImGuiKey::LeftShift,
        Key::LeftControl => ImGuiKey::LeftCtrl,
        Key::LeftAlt => ImGuiKey::LeftAlt,
        Key::LeftSuper => ImGuiKey::LeftSuper,
        Key::RightShift => ImGuiKey::RightShift,
        Key::RightControl => ImGuiKey::RightCtrl,
        Key::RightAlt => ImGuiKey::RightAlt,
        Key::RightSuper => ImGuiKey::RightSuper,
        _ => {
            // Ignore unknown keys
            return;
        }
    };

    io.add_key_event(igkey, pressed);
}

/// Handle changes in the key modifier states.
pub fn handle_key_modifier(io: &mut Io, keymod: &Modifiers) {
    // handle the actual modifiers:
    io.add_key_event(ImGuiKey::ModShift, keymod.intersects(Modifiers::Shift));
    io.add_key_event(ImGuiKey::ModCtrl, keymod.intersects(Modifiers::Control));
    io.add_key_event(ImGuiKey::ModAlt, keymod.intersects(Modifiers::Alt));
    io.add_key_event(ImGuiKey::ModSuper, keymod.intersects(Modifiers::Super));
}
